 ;file with objectscript lines to init iris
 zn "%SYS"
 Do ##class(Security.Users).UnExpireUserPasswords("*")

 ; enabling callin for Embedded Python
    do ##class(Security.Services).Get("%Service_CallIn",.prop)
    set prop("Enabled")=1
    set prop("AutheEnabled")=48
    do ##class(Security.Services).Modify("%Service_CallIn",.prop)


 ;do $System.OBJ.LoadDir("/home/irisowner/dev/src","ck",,1)
 ;
 ;

 zn "USER"
 zpm "load /home/irisowner/dev/"

 halt

